### ISSUE TITLE
Deletes all images

### ISSUE THREAD

**Issue by PostmanZero** [rickysullivan/gulp-delete-unused-images#12]
Hey, I don't know why, but it removes all the images for me. As if he didn't check the HTML file.

**Comment by marekp97** [comment]
The problem is probably here:
https://github.com/rickysullivan/gulp-delete-unused-images/issues/9

Detects correctly on macOS, on Windows all.

**Comment by PostmanZero** [comment]
I guess the problem is here:
https://github.com/rickysullivan/gulp-delete-unused-images/issues/9
It works on macOS, and on Windows, it detects all images. Can you fix it relatively soon?

**Comment by rickysullivan** [comment]
Will fix via the other issue.
