### ISSUE TITLE
delete:false works strange

### ISSUE THREAD

**Issue by lorvent** [rickysullivan/gulp-delete-unused-images#2]
when i use log:true, delete:false

first time its showing log and not deleting anything

with same configuration, if i run second time, its not showing log and deleting all files

**Comment by rickysullivan** [comment]
You're right. Sorry I had fixed this locally, but never pushed to github. Try now.

**Comment by lorvent** [comment]
Thanks for quick response,
i will try and update you.

**Comment by lorvent** [comment]
yeah, its working properly now
