### ISSUE TITLE
don`t work

### ISSUE THREAD

**Issue by davaynamore** [rickysullivan/gulp-delete-unused-images#5]
Hello, in our project path to images we write like this:
`<img src="<?=$base_url_img?>/sci-fi/a-light-in-the-forest-200x282.jpg"/>`
may be it is problem to plugin?

**Comment by rickysullivan** [comment]
Like?

**Comment by davaynamore** [comment]
sorry )

**Comment by rickysullivan** [comment]
It will search all supplied paths to the `gulp.src`.
