### ISSUE TITLE
Problem with minified .json and .css

### ISSUE THREAD

**Issue by leandrofngl** [rickysullivan/gulp-delete-unused-images#6]
The plugin works perfectly even in my .json and .css files, however when I minify the .json and .css files and run the gulp task then it does not identify the images used.

Note: When I minify my .css and .json it gets everything in 1 row

**Comment by rickysullivan** [comment]
I see. The way this works is that it reads the file line-by-line, looking for possible matches. Could you minify the files after running this plugin?

**Comment by leandrofngl** [comment]
My project was developed with Hugo, when I build the site already minify the files by Hugo that is much faster, but perhaps the solution is to build with hugo, then to remove the unused images and later minify with gulp. :(

But thanks for the agility in the response.
